name: flutter_staggered_grid_view
description: Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
version: 0.7.0
homepage: https://github.com/letsar/flutter_staggered_grid_view

environment:
  sdk: ">=3.7.0-0 <4.0.0"
  flutter: ">=3.18.0-18.0.pre.54"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter