name: examples
description: Example for collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.18.0-18.0.pre.54"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: any
  flutter_staggered_grid_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true